export const metadata = {
  title: 'React.js-and-Next.js-Project',
  description: 'Generated by React.js-Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
